<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ATHULYA-HARIKRISHNAN" failures="1" tests="1" name="testPackage.VerificationClass" time="7.740" errors="0" timestamp="2025-03-15T14:25:40 IST" skipped="0">
  <testcase classname="testPackage.VerificationClass" name="verify" time="7.740">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at testPackage.VerificationClass.verify(VerificationClass.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
    <system-out>
      <![CDATA[verify testcase execution started]]>
    </system-out>
  </testcase> <!-- verify -->
  <system-out>
    <![CDATA[Execution Started
printData testcase execution started
printData testcase execution started
printData testcase execution started
printData testcase execution started
printData17 testcase execution started
printData17 testcase execution started
printData17 testcase execution started
printData17 testcase execution started
contactDetails testcase execution started
contactDetails testcase execution started
printData testcase execution started
printData testcase execution started
printData testcase execution started
printData testcase execution started
printData1 testcase execution started
printData1 testcase execution started
printData1 testcase execution started
printData1 testcase execution started
createContact testcase execution started
createContact testcase execution started
moveToCalendarPage testcase execution started
moveToContactsPage testcase execution started
moveToLeadsPage testcase execution started
moveToOrganizationsPage testcase execution started
createOrganization testcase execution started
verify testcase execution started
TestCase3 testcase execution started
TestCase4 testcase execution started]]>
  </system-out>
</testsuite> <!-- testPackage.VerificationClass -->
